language: node_js
node_js:
  - '8'
sudo: false
dist: trusty
addons:
  chrome: stable
before_script:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
yarn: true
env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

stages:
  - 'Tests'
  - 'Additional Tests'
  - name: 'Deploy'
    if: branch = master AND type = push

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: 'Tests'
      name: 'Fixed Dependencies'
      install:
        - yarn install --non-interactive
      script:
        - yarn lint:hbs
        - yarn lint:js
        - yarn test
    - name: 'Floating Dependencies'
      script:
        - yarn test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: 'Additional Tests'
      env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

    - stage: 'Deploy'
      name: 'Publish to npm'
      install:
        - yarn install --non-interactive
      script: yarn semantic-release

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive --skip-optional
  - yarn global add codecov
script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
