language: node_js
node_js:
  - '8'
sudo: false
dist: trusty
addons:
  chrome: stable
before_script:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

script:
  - yarn lint:js
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

stages:
  - basic test
  - additional tests
jobs:
  fail_fast: true
  include:
    - stage: basic test
      env: EMBER_TRY_SCENARIO=ember-release
    - stage: additional tests
      env: EMBER_TRY_SCENARIO=ember-lts-2.12
    - env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-beta
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
